@startuml
scale 1.1
title I/O multiplexing model
hide footbox
skinparam monochrome true
skinparam defaultFontName Source Sans Pro
skinparam titleFontSize 15
skinparam sequenceMessageAlign center

activate application
application->>kernel: monitoring\ndescriptors
deactivate application
activate kernel
Note right of kernel: wait for data\nin at least one\ndescriptor
kernel-->>application: readable\ndescriptors
deactivate kernel
activate application
application->>kernel: reading data
deactivate application
activate kernel
Note right of kernel: copy data
kernel-->>application: data
deactivate kernel
activate application

||11||
kernel -[#white]->]
@enduml
